customers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('logout', views.logout, name='logout'),
]

inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='inventory'),
]

libms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('materials/', include('materials.urls')),
    path('customers/', include('customers.urls')),
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

materials/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='materials'),
    path('<int:material_id>', views.checkout, name='checkout')
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

customers/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models

# Create your models here.

librarians/models.py
from django.db import models

# Create your models here.

materials/models.py
from django.db import models

from django.contrib.auth.models import User


class Material(models.Model):
    materialChoices = [
        ('B', 'Book'),
        ('M', 'Magazine'),
    ]
    title = models.CharField(max_length=200)
    materialType = models.CharField(max_length=1, choices=materialChoices,)
    def __str__(self):
        return self.title

class InventoryItem(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    material_id = models.ForeignKey(Material, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True)
    deadline = models.DateField(auto_now_add=False)
    def __str__(self):
        return self.material_id.title

pages/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        # get form values
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        # check if passwords match
        if password == password2:
            # check username
            if User.objects.filter(username=username).exists():
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return redirect('login')
    else: 
        return render(request, 'customers/register.html')
    
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('dashboard')
        else:
            return redirect('login')
    else: 
        return render(request, 'customers/login.html')
    
def dashboard(request):
    return render(request, 'customers/dashboard.html')
    
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('index')

inventory/views.py
from django.shortcuts import render

from materials.models import InventoryItem

def index(request):
    inventory = InventoryItem.objects.filter(user_id=request.user)
    context = {
        'inventory' : inventory
    }
    return render(request, 'inventory/inventory.html', context)

librarians/views.py
from django.shortcuts import render

# Create your views here.

materials/views.py
from django.shortcuts import render, redirect

from datetime import datetime, timedelta

from .models import Material, InventoryItem

def index(request):
    materials = Material.objects.all()

    context = {
        'materials': materials
    }

    return render(request, 'materials/materials.html', context)

def checkout(request, material_id):
    material = Material.objects.get(pk=material_id)
    if material is not None:
        timestamp = datetime.now()
        if material.materialType == 'B':
            deadline = timestamp + timedelta(days=30)
        else:
            deadline = timestamp + timedelta(days=7)
        inventory_item = InventoryItem.objects.create(user_id=request.user, material_id=material, timestamp=timestamp, deadline=deadline)
        inventory_item.save()
    return redirect('materials')

pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

def about(request):
    return render(request, 'pages/about.html')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>LibMS</title>
  </head>
  <body>

    {% include 'partials/_navbar.html' %}

    {% block content %}{% endblock %}

    {% include 'partials/_footer.html' %}

    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/customers/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <h4 class="text-center">Dashboard</h4>
    <div class="container">
        
    </div>
{% endblock %}

templates/customers/login.html
{% extends 'base.html' %}
{% block content %}
<h4 class="text-center">Login</h4>
<div class="container">
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
</div>
{% endblock %}

templates/customers/register.html
{% extends 'base.html' %}
{% block content %}
<h4 class="text-center">Register</h4>
<div class="container">
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password">
        </div>
        <div class="form-group">
          <label for="password2">Confirm password</label>
          <input type="password" class="form-control" id="password2" name="password2">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
      </form>
</div>
{% endblock %}

templates/inventory/inventory.html
{% extends 'base.html' %}
{% block content %}
    <h4 class="text-center">Inventory</h4>
    <section id="inventory" class="py-4">
        <div class="container">
            <div class="row">
                {% if inventory %}
                    {% for item in inventory %}
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card p-3">
                               <h5 class="card-title">{{ item.material_id.title }}</h5>
                               <p class="card-text">{{ item.material_id.get_materialType_display }}</p>
                               <p class="card-text">{{ item.timestamp }}</p>
                               <p class="card-text">{{ item.deadline }}</p>
                               <a href="#" class="btn btn-primary btn-sm">Check-in</a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-12">
                        <p class="text-center">Inventory empty.</p>
                    </div>
                {% endif %}
    
            </div>
        </div>
    </section>
{% endblock %}

templates/materials/materials.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mt-4">Materials</h1>
<section id="materials" class="py-4">
    <div class="container">
        <div class="row">
            {% if materials %}
                {% for material in materials %}
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card p-3">
                           <h5 class="card-title">{{ material.title }}</h5>
                           <p class="card-text">{{ material.get_materialType_display }}</p>
                           <a href="{% url 'checkout' material.id %}" class="btn btn-primary btn-sm">Check-out</a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <p>No materials available</p>
                </div>
            {% endif %}

        </div>
    </div>
</section>
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About</h1>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Home</h1>
{% endblock %}

templates/partials/_footer.html
<footer class="my-5 pt-5 text-muted text-center text-small bg-dark">
    <p class="mb-1 text-light">&copy; 2020 LibMS</p>
    <br>
</footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">LibMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a
        {% if '/' == request.path %}
            class="nav-item nav-link active"
        {% else %}
            class="nav-item nav-link"
        {% endif %}
        href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        <a 
        {% if 'about' in request.path %}
            class="nav-item nav-link active"
        {% else %}
            class="nav-item nav-link"
        {% endif %}
         href="{% url 'about' %}">About</a>
         {% if user.is_authenticated %}
            <a 
            {% if 'materials' in request.path %}
                class="nav-item nav-link active"
            {% else %}
                class="nav-item nav-link"
            {% endif %}
            href="{% url 'materials' %}">Materials</a>
            <a 
            {% if 'inventory' in request.path %}
                class="nav-item nav-link active"
            {% else %}
                class="nav-item nav-link"
            {% endif %}
            href="{% url 'inventory' %}">Inventory</a>
            <a 
            {% if 'dashboard' in request.path %}
                class="nav-item nav-link active"
            {% else %}
                class="nav-item nav-link"
            {% endif %}
            href="{% url 'dashboard' %}">Dashboard</a>
            <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}">Logout</a>
            <form action="{% url 'logout' %}" method="POST" id="logout">
                {% csrf_token %}
                <input type="hidden">
            </form>
         {% else %}
            <a 
            {% if 'login' in request.path %}
                class="nav-item nav-link active"
            {% else %}
                class="nav-item nav-link"
            {% endif %}
            href="{% url 'login' %}">Login</a>
            <a 
            {% if 'register' in request.path %}
                class="nav-item nav-link active"
            {% else %}
                class="nav-item nav-link"
            {% endif %}
            href="{% url 'register' %}">Register</a>
         {% endif %}
      </div>
    </div>
  </nav>